CREATE TABLE TABLE_NOTNULL (
        LOGIN_ID VARCHAR2(20) NOT NULL,
        LOGIN_PWD VARCHAR2(20) NOT NULL,
        TEL VARCHAR2(20)
);

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD)
    VALUES ('TEST_ID_O1', '1234');

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, R_OWNER, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN ('EMP', 'DEPT');

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'CLERK', '7788', TO_DATE('2017-04-30', 'YYYY-MM-DD'), 1200, NULL, 50);


CREATE TABLE DEPT_FK (
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY ,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

DESC DEPT_FK;

COMMIT;

CREATE TABLE EMP_FK (
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY ,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DESC EMP_FK; /*오라클 기반에서만*/
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE '테이블명';

SELECT * FROM USER_TABLES;


INSERT INTO EMP_FK
VALUES (9999, 'TEST_NAME', 'TEST_JOB', 'NULL', TO_DATE('2017-04-30', 'YYYY-MM-DD'), 3000, NULL, 10);

INSERT INTO DEPT_FK
    VALUES (10, 'TEST_DNAME', 'TEST_DOC');

DELETE FROM DEPT_FK WHERE DEPTNO = 10;

UPDATE DEPT_FK SET DEPTNO = NULL WHERE DEPTNO = 10;

SELECT * FROM DEPT_FK;

INSERT INTO EMP_FK
    VALUES (9999,'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2017-04-30', 'YYYY-MM-DD'), 3000, NULL, 10);

SELECT * FROM EMP_FK;

COMMIT ;

-- CHECK 제약 조건: 값의 범위 또는 패턴을 정의할 때 사용하는 제약 조건
CREATE TABLE TABLE_CHECK (
        LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY ,
        LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK ( LENGTH(LOGIN_PWD) > 3 ),
        TEL VARCHAR2(20)
);

DESC TABLE_CHECK;

INSERT INTO TABLE_CHECK
    VALUES ('TEST_ID', '123', '010-1234-5678');

INSERT INTO TABLE_CHECK
VALUES ('TEST_ID', '1234', '010-1234-5678');

SELECT * FROM TABLE_CHECK;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_DEFAULT';

CREATE TABLE TABLE_DEFAULT (
     LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY ,
     LOGIN_PWD VARCHAR2(20) DEFAULT '1234'
);

INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID', NULL);
INSERT INTO TABLE_DEFAULT(LOGIN_ID) VALUES ('TEST_ID2');

SELECT * FROM TABLE_DEFAULT;


-- 제약조건 비활성화
ALTER TABLE TABLE_DEFAULT DISABLE CONSTRAINT
